name: IO-NightVision
main: org.iocraft.nightvision.Main
version: 1.0.0
description: IO-NightVision is a plugin designed for a simple night vision ability and permission.
author: ioCraft.org Team
website: https://www.iocraft.org

commands:
   accounts:
      description: Includes info and reloads.
      usage: /accounts <help, reload>
   nv:
      description: Toggles night vision.
      usage: /nv
      permission: io.nightvision.nv
      permission-message: You don't have <permission>

permissions:
    io.nightvision.*:
        description: Gives access to all IO-NightVision commands.
        children:
            io.nightvision.player.*: true
            io.nightvision.reload: true
    io.nightvision.player.*:
        description: Gives access to all player commands.
        children:
            io.nightvision.help: true
            io.nightvision.nv: true
            io.nightvision.reload: false
    io.nightvision.help:
        description: Show a list of commands for IO-NightVision.
        default: true
    io.nightvision.nv:
        description: Toggles night vision.
        default: true
    io.nightvision.reload:
        description: Reload the configuration.
        default: op