name: IO-Gamma
main: org.iocraft.gamma.Main
version: 1.0.0
description: IO-Gamma is a plugin designed for a simple night vision ability and permission.
author: ioCraft.org Team
website: https://www.iocraft.org

commands:
   accounts:
      description: Includes info and reloads.
      usage: /accounts <help, reload>
   nv:
      description: Toggles night vision.
      usage: /nv
      permission: io.gamma.nv
      permission-message: You don't have <permission>

permissions:
    io.gamma.*:
        description: Gives access to all IO-Gamma commands.
        children:
            io.gamma.player.*: true
            io.gamma.reload: true
    io.gamma.player.*:
        description: Gives access to all player commands.
        children:
            io.gamma.help: true
            io.gamma.nv: true
            io.gamma.reload: false
    io.gamma.help:
        description: Show a list of commands for IO-Gamma.
        default: true
    io.gamma.nv:
        description: Toggles night vision.
        default: true
    io.gamma.reload:
        description: Reload the configuration.
        default: op